require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['SWIFT_VERSION'] = '5'

platform :ios, '11.0'
use_frameworks!

target 'SDKsExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'DocumentDetector', '6.2.0'
  pod 'PassiveFaceLiveness', '5.7.0'
  pod 'FaceAuthenticator', '5.1.0'

  target 'SDKsExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'SDKsExample-tvOS' do
  # Pods for SDKsExample-tvOS

  target 'SDKsExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

source 'https://github.com/combateafraude/iOS.git'
source 'https://cdn.cocoapods.org/'
